name: 'action-parse-asdf-tool-versions'
description: 'Parse asdf managed .tool-versions and outputs them'
author: 'Kenichi Kamiya <kachick1@gmail.com>'
branding:
  icon: 'eye'
  color: 'blue'
runs:
  using: 'composite'
  steps:
    - run: cat .tool-versions | cabal v2-run -v0 "$GITHUB_ACTION_PATH/app/Main.hs" | echo "json=$(</dev/stdin)" | tee --append $GITHUB_OUTPUT
      shell: bash
      id: parser
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}
outputs:
  json:
    description: 'Stringified JSON for parsed .tool-versions'
    value: '${{ steps.parser.outputs.json }}'
