name: 'action-parse-asdf-tool-versions'
description: 'Parse asdf managed .tool-versions and outputs them'
author: 'Kenichi Kamiya <kachick1@gmail.com>'
branding:
  icon: 'eye'
  color: 'blue'
runs:
  using: 'composite'
  steps:
    - name: Cache cabal
      id: cache-cabal
      uses: actions/cache@v3
      with:
        path: dist-newstyle
        key: ${{ runner.os }}-cabal-dist-${{ hashFiles('src/**', 'app/**', '*.cabal') }}
    - run: cat .tool-versions | cabal v2-run -v0 action-parse-asdf-tool-versions | echo "json=$(</dev/stdin)" | tee --append $GITHUB_OUTPUT
      shell: bash
      id: parser
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}
outputs:
  json:
    description: 'Stringified JSON for parsed .tool-versions'
    value: '${{ steps.parser.outputs.json }}'
