name: 'action-parse-asdf-tool-versions'
description: 'Parse asdf managed .tool-versions and outputs them'
author: 'Kenichi Kamiya <kachick1@gmail.com>'
branding:
  icon: 'eye'
  color: 'blue'
runs:
  using: 'composite'
  steps:
    - name: logging tool versions
      run: ruby -v
      shell: bash
    - name: Parse .tool-versions and converts to JSON
      run: cat ${{ inputs.tool-versions-path }} | ruby "$GITHUB_ACTION_PATH/scripts/asdf2json.rb" | echo "json=$(</dev/stdin)" | tee -a $GITHUB_OUTPUT
      shell: bash
      id: parser
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}
inputs:
  tool-versions-path:
    description: 'Path of .tool-versions'
    required: true
    default: '.tool-versions'
outputs:
  json:
    description: 'Stringified JSON for parsed .tool-versions'
    value: '${{ steps.parser.outputs.json }}'
