name: 'action-parse-asdf-tool-versions'
description: 'Parse asdf managed .tool-versions and outputs them'
author: 'Kenichi Kamiya <kachick1@gmail.com>'
branding:
  icon: 'eye'
  color: 'blue'
runs:
  using: 'composite'
  steps:
    - name: gather haskell versions
      run: |
        echo "ghc=$(ghc --numeric-version)" | tee --append $GITHUB_OUTPUT
        echo "cabal=$(cabal --numeric-version)" | tee --append $GITHUB_OUTPUT
      shell: bash
      id: haskell-versions
    - name: Cache cabal global
      id: cache-cabal-global
      uses: actions/cache@v3
      with:
        path: ~/.cabal
        key: ${{ runner.os }}-ghc-${{ steps.haskell-versions.outputs.ghc }}-cabal-${{ steps.haskell-versions.outputs.cabal }}-cabal-global-${{ hashFiles("$GITHUB_ACTION_PATH/src/**", "$GITHUB_ACTION_PATH/app/**", "$GITHUB_ACTION_PATH/*.cabal") }}
    - name: Cache cabal work
      id: cache-cabal-local
      uses: actions/cache@v3
      with:
        path: dist-newstyle
        key: ${{ runner.os }}-ghc-${{ steps.haskell-versions.outputs.ghc }}-cabal-${{ steps.haskell-versions.outputs.cabal }}-cabal-local-${{ hashFiles("$GITHUB_ACTION_PATH/src/**", "$GITHUB_ACTION_PATH/app/**", "$GITHUB_ACTION_PATH/*.cabal") }}
    - name: Parse .tool-versions and converts to JSON
      run: |
        tool_versions_path=$(readlink -f .tool-versions)
        cd $GITHUB_ACTION_PATH
        cat "$tool_versions_path" | cabal v2-run -v0 action-parse-asdf-tool-versions | echo "json=$(</dev/stdin)" | tee --append $GITHUB_OUTPUT
      shell: bash
      id: parser
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}
outputs:
  json:
    description: 'Stringified JSON for parsed .tool-versions'
    value: '${{ steps.parser.outputs.json }}'
