name: CI - Haskell
on:
  push:
    branches: [main]
    paths:
      - '.github/haskell.yml'
      - 'app/**'
      - 'src/**'
      - 'test/**'
      - '.tool-versions'
  pull_request:
    paths:
      - '.github/haskell.yml'
      - 'app/**'
      - 'src/**'
      - 'test/**'
      - '.tool-versions'
  workflow_dispatch:

jobs:
  haskell:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - run: cabal test
