name: Test
on:
  push:
    branches: [main]
    paths-ignore:
      - '.github/dependabot.yml'
      - '.github/workflows/haskell.yml'
      - '.github/workflows/dprint.yml'
      - '.github/workflows/dependency-review.yml'
      - '.github/workflows/merge-bot-pr.yml'
      - '.editorconfig'
      - 'dprint.json'
      - 'README.md'
      - '.vscode/**'
  pull_request:
    paths-ignore:
      - '.github/dependabot.yml'
      - '.github/workflows/haskell.yml'
      - '.github/workflows/dprint.yml'
      - '.github/workflows/dependency-review.yml'
      - '.github/workflows/merge-bot-pr.yml'
      - '.editorconfig'
      - 'dprint.json'
      - 'README.md'
      - '.vscode/**'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - name: logging tool versions
        run: ruby -v
      - run: ruby test/asdf_test.rb
