name: Validate
on:
  push:
    branches: [main]
    paths-ignore:
      - '.github/dependabot.yml'
      - '.github/workflows/haskell.yml'
      - '.github/workflows/dprint.yml'
      - '.github/workflows/dependency-review.yml'
      - '.github/workflows/merge-bot-pr.yml'
      - '.editorconfig'
      - 'dprint.json'
      - 'README.md'
      - '.vscode/**'
  pull_request:
    paths-ignore:
      - '.github/dependabot.yml'
      - '.github/workflows/haskell.yml'
      - '.github/workflows/dprint.yml'
      - '.github/workflows/dependency-review.yml'
      - '.github/workflows/merge-bot-pr.yml'
      - '.editorconfig'
      - 'dprint.json'
      - 'README.md'
      - '.vscode/**'
  workflow_dispatch:

jobs:
  parser:
    strategy:
      fail-fast: false
      # Syntax https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs
      matrix:
        # os: ['ubuntu-latest', 'macos-latest']
        os: ['ubuntu-latest']
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        id: asdf_parser
        with:
          tool-versions-path: 'example/.tool-versions'
    outputs:
      tool-versions: '${{ steps.asdf_parser.outputs.json }}'
  validate: # make sure the action works on a clean machine
    needs: [parser]
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - run: echo '${{ needs.parser.outputs.tool-versions.shfmt }}' | grep -P '\A\d+\.\d+\.\d+\z'
      - run: echo '${{ fromJson(needs.parser.outputs.tool-versions).shellcheck }}' | grep -P '\A\d+\.\d+\.\d+\z'
      - run: test '18.11.0' = '${{ fromJson(needs.parser.outputs.tool-versions).nodejs }}'
